"""add Department

Revision ID: 32fc75819b1f
Revises: 602392efb3e0
Create Date: 2025-11-10 19:47:17.392528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32fc75819b1f'
down_revision = '602392efb3e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.String(), nullable=True))
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.VARCHAR(), nullable=True))
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###
