"""rename address

Revision ID: 602392efb3e0
Revises: e57b67b3daf3
Create Date: 2025-05-12 21:26:43.712703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602392efb3e0'
down_revision = 'e57b67b3daf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.String(), nullable=True))
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###
