"""rename address

Revision ID: 602392efb3e0
Revises: e57b67b3daf3
Create Date: 2025-05-12 21:26:43.712703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602392efb3e0'
down_revision = 'e57b67b3daf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###