"""rename department

Revision ID: e57b67b3daf3
Revises: d14d972b0ef5
Create Date: 2025-05-12 21:22:18.873666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57b67b3daf3'
down_revision = 'd14d972b0ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments', new_column_name='location')
    # ### end Alembic commands ###
 


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department', new_column_name='address')
    # ### end Alembic commands ###
